name: Test AI Analysis Engine

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/analysis/**'
      - 'tests/**'
      - '.github/workflows/test-analysis.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/analysis/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync
    
    - name: Run unit tests with mocking
      run: |
        uv run pytest tests/test_analysis_integration.py -v \
          --cov=src.analysis \
          --cov-report=xml \
          --cov-report=term-missing \
          -k "not integration"
    
    - name: Run integration tests (if API key available)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY_TEST }}
      run: |
        if [ ! -z "$ANTHROPIC_API_KEY" ]; then
          uv run pytest tests/test_analysis_integration.py -v -m integration
        else
          echo "Skipping integration tests - no API key configured"
        fi
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
    
    - name: Generate coverage badge
      run: |
        uv run coverage html
        echo "Coverage report generated in htmlcov/"
    
    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
    
    - name: Check test coverage threshold
      run: |
        uv run coverage report --fail-under=80
    
  performance-test:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync
    
    - name: Run performance benchmarks
      run: |
        uv run pytest tests/test_analysis_integration.py::TestPerformance -v --benchmark-only
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: .benchmarks/